### PR TITLE
Type definitions for TypeScript support

### LINKED ISSUE #33: TypeScript support?
I'm writing my application in TypeScript and would like to see TypeScript typing support.

### PR DESCRIPTION
**Pull request by universalhandle**
Proposed alternative to #41; closes #33.

I tried to be as selective as possible as far as what to write type declarations for. Hopefully I erred on the side of typing too little and keeping TypeScript ignorant of the internal workings of this library.

### CODE REVIEW

**Comment by universalhandle** [comment]
@glensc, if you could have a look at this when you get a chance, I'd appreciate it!

**Comment by glensc** [comment]
@universalhandle please instructions for me and posterity how to use this branch

**Comment by universalhandle** [comment]
Your `package.json` should look like this:

```
  "dependencies": {
    [ ... ]
    "@tedconf/fessonia": "universalhandle/fessonia#type-defs",
    [ ... ]
  }
```

Unlike the other PR, there's no need to run any "generate" commands.

If you don't like editing your `package.json` manually, see Stackoverflow answers for [npm](https://stackoverflow.com/a/39732501/1828069) and [yarn](https://stackoverflow.com/a/49992734/1828069) (note: I don't use yarn and can't confirm these commands).

**Comment by glensc** [comment]
@universalhandle got some tsc errors. i'll pass them on here:

```
$ tsc --declaration
node_modules/@tedconf/fessonia/types/lib/ffmpeg_progress_emitter.d.ts:34:9 - error TS2411: Property 'out_time' of type 'string | undefined' is not assignable to string index type 'string | number'.

34         out_time?: string;
           ~~~~~~~~

node_modules/@tedconf/fessonia/types/lib/ffmpeg_progress_emitter.d.ts:35:9 - error TS2411: Property 'out_time_ms' of type 'number | undefined' is not assignable to string index type 'string | number'.

35         out_time_ms?: number;
           ~~~~~~~~~~~

node_modules/@tedconf/fessonia/types/lib/ffmpeg_progress_emitter.d.ts:36:9 - error TS2411: Property 'out_time_us' of type 'number | undefined' is not assignable to string index type 'string | number'.

36         out_time_us?: number;
           ~~~~~~~~~~~

src/EncodeCommand.ts:50:30 - error TS2345: Argument of type '{ hide_banner: null; y: null; }' is not assignable to parameter of type 'Options'.
  Type '{ hide_banner: null; y: null; }' is missing the following properties from type 'Options': clear, delete, forEach, get, and 8 more.

50     return new FFmpegCommand({ ...this.commandOptions, ...options });
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors.
```

**Comment by universalhandle** [comment]
Whoops. Sorry about that. Looks like the fix(es) will be easy, though.

I wonder what I did differently than you that I didn't also see that. Can you say a little bit about how you encountered these so I can be sure not to miss any more mistakes?

Thanks!

**Comment by glensc** [comment]
I did nothing else, other than add dependency and run `tsc`, the errors are from `tsc`. perhaps the typescript version matters? mine was `typescript@^3.9.7`.

**Comment by glensc** [comment]
and `tsconfig.json` maybe matters:

```json
// https://www.typescriptlang.org/docs/handbook/compiler-options.html
{
  "compilerOptions": {
    // Redirect output structure to the directory.
    "outDir": "build",
    // Enable all strict type-checking options.
    "strict": true,
    // Stylize errors and messages using color and context (experimental).
    "pretty": true,
    // Specify module code generation: 'commonjs', 'amd', 'system', 'umd' or 'es2015'.
    "module": "commonjs",
    // Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6).
    "moduleResolution": "node",
    // Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', or 'ESNEXT'
    "target": "ES2017",
    // Enables experimental support for ES7 decorators.
    "experimentalDecorators": true,
    "esModuleInterop": true,
    // List of folders to include type definitions from.
    "typeRoots": [
      "./node_modules/@types",
      "./typings"
    ],
    // List of library files to be included in the compilation
    "lib": [
      "dom",
      "es6",
      "esnext"
    ]
  },
  "include": [
    "src/**/*.ts"
  ]
}
```

**Comment by nihonjinrxs** [comment]
So far this looks pretty good to me, from a library interface coverage standpoint. (I only poke at TypeScript, so I can't evaluate that well.)

When you have both settled on what you want to do (#41 or #44, and whether either still needs modification), let me know, and I'll see if I can get a dummy TS project up using the types to validate them.

Also, in order to prevent the possibility of a future version interface change breaking the types and me not realizing it, is there a way to script something like an automated type consistency test? What would that entail? Just trying to ensure I can more easily maintain what come out of this.

Thanks again for the help, @glensc and @universalhandle.

**Comment by nihonjinrxs** [comment]
Just noting that you've both been added (or updated) in the contributors here on Github, and on [the docs site](https://tedconf.github.io/fessonia/fessonia/current/tutorial-3_about_fessonia.html).

@universalhandle please pull master into your branch when you get a chance. Thanks.

**Comment by universalhandle** [comment]
Okay, I created a new dummy project with your tsconfig and found the bug. My actual project doesn't have `strict: true` because it's a converted JavaScript codebase that is still working its way toward Typescript majesty. I'm glad you found this -- thank you, @glensc!

If anyone's interested, the problem was that the definitions for specific optional properties in the `ProgressData` interface were inconsistent with the generic property definition:
```
    export interface ProgressData {
        out_time?: string;
        out_time_ms?: number;
        out_time_us?: number;
        [key: string]: string | number;
    }
```
To correct that I had to change the generic one to this:
```
        [key: string]: string | number | undefined;
```
If @glensc approves, I'm happy to see this get merged.

As for @nihonjinrxs's question:
> Also, in order to prevent the possibility of a future version interface change breaking the types and me not realizing it, is there a way to script something like an automated type consistency test? What would that entail? Just trying to ensure I can more easily maintain what come out of this.

I am not aware of any tools for this. Some light research I did suggested "the most reliable future-proof way would be to port the project to TypeScript and have the type definitions generated automatically by tsc," which is not much of an answer for a maintainer who is not interested in TypeScript!

The library isn't huge. This seems like something I can help maintain if we can communicate around releases (to give me enough time to see what's changed before you flick the switch).

**Comment by nihonjinrxs** [comment]
@universalhandle Thanks for the offer to help maintain the TypeScript types piece of this. I'd love to have your help with that. There may be times where we'll need to release quickly because a new feature/bugfix is needed internally, but I can definitely let you know via tagging you in an issue when there are API changes to look at for potential type updates, and will try to do that as soon as I know we're making those changes.

**Comment by nihonjinrxs** [comment]
@universalhandle Thanks for the offer to help maintain the TypeScript types piece of this. I'd love to have your help with that. There may be times where we'll need to release quickly because a new feature/bugfix is needed internally, but I can definitely let you know via tagging you in an issue when there are API changes to look at for potential type updates, and will try to do that as soon as I know we're making those changes.

**Comment by universalhandle** [comment]
Hi, @nihonjinrxs and @glensc. Do you think you'll have a chance to review/merge this this week? My downstream project is getting close to being ready for release, and I'd prefer not to create a dependency on my fork of this repo. Thanks!

**Comment by glensc** [comment]
@universalhandle same error, as like unable to pull your updates.

```
$ yarn add @tedconf/fessonia@'universalhandle/fessonia#type-defs'
```

trying with a commit then:
```
$ yarn add @tedconf/fessonia@'universalhandle/fessonia#29eca92'
```

better, but still errors:
```
$ tsc
src/EncodeCommand.ts:50:30 - error TS2345: Argument of type '{ hide_banner: null; y: null; }' is not assignable to parameter of type 'Options'.
  Type '{ hide_banner: null; y: null; }' is missing the following properties from type 'Options': clear, delete, forEach, get, and 8 more.

50     return new FFmpegCommand({ ...this.commandOptions, ...options });
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by universalhandle** [comment]
> @universalhandle same error, as like unable to pull your updates.
> 
> ```
> $ yarn add @tedconf/fessonia@'universalhandle/fessonia#type-defs'
> ```

Thanks for trying again, @glensc. This sounds to me like a caching problem. Are you able to delete `package-lock.json` and `node_modules` from your project and reinstall? When you install it this way, npm puts a reference to the commit at the head of the branch in the lock file.

> trying with a commit then:
> 
> ```
> $ yarn add @tedconf/fessonia@'universalhandle/fessonia#29eca92'
> ```

Oh, or that. That should work :-)

> better, but still errors:
> 
> ```
> $ tsc
> src/EncodeCommand.ts:50:30 - error TS2345: Argument of type '{ hide_banner: null; y: null; }' is not assignable to parameter of type 'Options'.
>   Type '{ hide_banner: null; y: null; }' is missing the following properties from type 'Options': clear, delete, forEach, get, and 8 more.
> 
> 50     return new FFmpegCommand({ ...this.commandOptions, ...options });
>                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Found 1 error.
> ```

I think I see what's happened here. My type declaration says the `options` argument to the FFmpegCommand constructor must be a Map. I typed it that way because that seems to be the preference of the code, and the value is converted to a map if it wasn't already one.

And this approach works fine if you're writing new code (your IDE will hint you as to the argument types), but if you have existing code that depends on the make-it-a-map-for-me behavior, well, I've just broken transpilation for you :-) Bad on me for being so prescriptive.

This happens a few other places in the code. I'll have a look today/tomorrow and try to get this appropriately permissive. Thanks for your patience and continued QA.

**Comment by universalhandle** [comment]
Hi, @glensc. Sorry it took me awhile to get back to this -- unfortunately other stuff came up. I gave it another pass and made a few adjustments, including one that should get you past the error you were seeing. Please try it out and report back when you can.

**Comment by glensc** [comment]
@universalhandle I suggest not to include any references, such as issue-id in commit messages (commit refs are the other kind), when rebasing, they create duplicate refs, which add no value. also wastes precious 50-72 char limit of the subject line. a fine place for references is a merge commit, which github does automatically.

**Comment by nihonjinrxs** [comment]
Thank you both for your continued work on this. It's very much appreciated.

**Comment by universalhandle** [comment]
@glensc, yes, I see these commits were unnecessarily noisy in GitHub. I forgot it would do that -- I've been using external issue trackers for all of my recent work. Will keep that in mind for future commits.

Did you have any luck getting your project to build with these latest changes? If not, and if you can share your code, perhaps things would go faster if I had your project to debug against.

**Comment by glensc** [comment]
@universalhandle, sorry, got side-tracked, tested now. Yes, `tsc` passes now. so LGTM and 💯 👍

**Comment by universalhandle** [comment]
Thank you! It looks like we're ready to merge, @nihonjinrxs.

**Comment by nihonjinrxs** [comment]
I'm merging this, and will release a new minor version (2.1.2 -> 2.2.0) and update the changelog accordingly. Thanks for all the dedicated work on this.

For future releases, I'll rely on @universalhandle to update the types accordingly. Thanks for the offer to do so. I'll communicate that via an issue _Update TS types for version x.y.z_ or similar, and tag you on it. Note that there may be situations where we have a critical deadline and need to release immediately; for those situations, type updates will need to come after the fact. We'll do our best to keep that to a minimum.

**Comment by universalhandle** [comment]
> I'm merging this, and will release a new minor version (2.1.2 -> 2.2.0) and update the changelog accordingly.

Brilliant! Thanks!

> For future releases, I'll rely on @universalhandle to update the types accordingly. Thanks for the offer to do so. I'll communicate that via an issue _Update TS types for version x.y.z_ or similar, and tag you on it. Note that there may be situations where we have a critical deadline and need to release immediately; for those situations, type updates will need to come after the fact. We'll do our best to keep that to a minimum.

All this sounds good. Since type definitions are essentially about ensuring API contracts remain consistent, I'm optimistic there won't be many cases where they have to be updated after the fact. It's not often that a project needs to break backward compatibility in a hurry.

Feel free to tag me liberally, in _Update TS types for version x.y.z_-type issues or any other.

**Comment by nihonjinrxs** [comment]
Much appreciated.

This release is live! https://www.npmjs.com/package/@tedconf/fessonia

**Comment by universalhandle** [comment]
Thanks. Do you not use git tags for release automation? (Obviously I was looking in the wrong place for the new release!)

**Comment by nihonjinrxs** [comment]
Sorry, didn't realize I didn't push the tag up. Should be there now.

**Comment by universalhandle** [comment]
I just noticed the new TS icon:
image

Cool!

**Comment by glensc** [comment]
I guess it's automatic by npm site?

**Comment by glensc** [comment]
@universalhandle since this did not include documentation, and phpstorm doesn't seem to be smart enough. I have a question, how do I import the types?

the only one that worked was this:
```ts
import FFmpegCommand from "@tedconf/fessonia/types/lib/ffmpeg_command";
```

but this looks ugly and makes rely on internal file structure, which I do not like, but I do see the same symbols are exported from index.ts.d

so:

```ts
import { FFmpegInput, FFmpegOutput } from "./Services/Fessonia";
import { ResqueStatus } from "./ResqueStatus";
import FFmpegCommand from "@tedconf/fessonia/types/lib/ffmpeg_command";
// import { FFmpegCommand } from "@tedconf/fessonia/types";
// import { FFmpegCommand } from "@tedconf/fessonia";

export abstract class EncodeCommand {
  private commandOptions : FFmpegCommand.Options = {
    "hide_banner": null,
    "y": null,
  };
...
```

my original problem was that when enabling `noImplicitAny`, the `null` values were treated as `any` and `tsc` complained:

```ts
export abstract class EncodeCommand {
  private commandOptions = {
    "hide_banner": null,
    "y": null,
  };
```

```
src/EncodeCommand.ts:6:5 - error TS7018: Object literal's property '"hide_banner"' implicitly has an 'any' type.

6     "hide_banner": null,
      ~~~~~~~~~~~~~~~~~~~

src/EncodeCommand.ts:7:5 - error TS7018: Object literal's property '"y"' implicitly has an 'any' type.

7     "y": null,
      ~~~~~~~~~

```

**Pull request merged**
