### PR TITLE
Fix progressData access on success event

### PR DESCRIPTION
**Pull request by glensc**
Re-generated docs according to:
- https://github.com/tedconf/fessonia/blob/master/docs/tutorials/4_contributing.md#generating-documentation

```
npm run generate-docs
```

### CODE REVIEW

**Comment by glensc** [comment]
seems the origin file is `docs/tutorials/0.0_getting_started.md`:

```
➔ git grep 'console.log(`Completed successfully with exit code'
docs/fessonia/0.0.7/tutorial-0_getting_started.html:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/0.0.7/tutorials/0_getting_started.md:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/0.0.8/tutorial-0_getting_started.html:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/0.0.8/tutorials/0_getting_started.md:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/0.0.9/tutorial-0_getting_started.html:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/0.0.9/tutorials/0_getting_started.md:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/1.0.0/tutorial-0_getting_started.html:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/1.0.0/tutorials/0_getting_started.md:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/1.0.1/tutorial-0_getting_started.html:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/1.0.1/tutorials/0_getting_started.md:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/2.0.0/tutorial-0_getting_started.html:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/2.0.0/tutorials/0_getting_started.md:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/2.1.0/tutorial-0.0_getting_started.html:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/2.1.0/tutorial-0_getting_started.html:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/2.1.0/tutorials/0.0_getting_started.md:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/fessonia/2.1.0/tutorials/0_getting_started.md:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
docs/tutorials/0.0_getting_started.md:  console.log(`Completed successfully with exit code ${data.exitCode}`, data.progressData);
```

**Comment by nihonjinrxs** [comment]
Thanks for the contribution, @glensc ! Much appreciated!

I'll take a look at this later this afternoon, but in the meantime, could you create a corresponding issue that describes the problem you were fixing here, and link this PR to it?

**Comment by glensc** [comment]
there's no issue, I just noticed wrong documentation when copied example to my project.

**Comment by nihonjinrxs** [comment]
fixes #35

**Pull request merged**
