### PR TITLE
Typescript types

### LINKED ISSUE #33: TypeScript support?
I'm writing my application in TypeScript and would like to see TypeScript typing support.

### PR DESCRIPTION
**Pull request by nihonjinrxs**
Closes #33 

Use [guide in TypeScripting Handbook](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html) to generate `.d.ts` files from `.js` files.

Also added a corresponding `tsconfig.json` file with configurations for this, as well as a new npm script in the `package.json` file to assist with this: `npm run generate-types`.

@glensc Please review and let me know if these type files (in the `types` folder) would suit your needs.

### CODE REVIEW

**Comment by glensc** [comment]
from quick view this import as type looks weird:

```
    static wrap(filterNode: import("./filter_node") | FilterChain): FilterChain;
```

I can't promise when I'll test with actually importing this branch.

**Comment by glensc** [comment]
To add this branch as dependency:

```
$ yarn add https://github.com/tedconf/fessonia#typescript-types
```

**Comment by glensc** [comment]
I believe you need to declare "types" in your "package.json" as well:

```
--- node_modules/@tedconf/fessonia/package.json~    2020-12-05 14:50:31.000000000 +0200
+++ node_modules/@tedconf/fessonia/package.json    2020-12-05 14:50:32.000000000 +0200
@@ -3,6 +3,7 @@
   "version": "2.1.2",
   "description": "A node module easing the burden of automating ffmpeg from node.js",
   "main": "index.js",
+  "types": "types/index.d.ts",
   "publishConfig": {
     "registry": "https://registry.npmjs.org/",
     "access": "public"
(END)
```

**Comment by glensc** [comment]
After `package.json` change and types compilation it works. `tsc` passes.

My test script:

```typescript
import getFessonia from "@tedconf/fessonia";

const fessonia = getFessonia({
  debug: true,
  log_warnings: true
});

export const { FFmpegCommand, FFmpegInput, FFmpegOutput } = fessonia;

```

**Comment by glensc** [comment]
Not sure is it a good idea to commit generated types, especially tons of type files for tests. otherwise LGTM.

**Review by glensc — APPROVED** [review]

**Comment by universalhandle** [comment]
Hello. Total newcomer to your project here. I have some experience doing typings, and I think a more considered approach is called for here. A lot of the return types produced by the autogenerated code are `any`, which is not very useful to Typescript developers.

From a maintainability point of view, I think it would be preferable to incrementally type the external interfaces of the library than to add 44 well-intentioned but ultimately not very useful files to the repository.

I can't promise anything yet, but I may be able to help you get this started. I'm scoping out this library for a project, and if (1) the project goes forward, and (2) we end up using this library for it, I'll need to write types for at least the interfaces I use. I know that's a few ifs, but I'm happy to contribute this work back to the project if things work out. I should know more in next week or so.

**Comment by glensc** [comment]
@universalhandle maybe this is a starting point, generate once the types, commit them, but maintain them manually. and definitely omit the generated types for test files.

anyway, for any of this to work `package.json` change must be committed, as I already mentioned:
- https://github.com/tedconf/fessonia/pull/41#issuecomment-739246968

**Comment by universalhandle** [comment]
Looks like I'm going to be able to work on this. I'll send an update in early Jan.

**Comment by nihonjinrxs** [comment]
Closing in favor of #44

**Pull request closed without merging**
